apiVersion: v1
kind: Service
metadata:
  name: k8s-service #The name of the Service.
spec:
  selector: #Specifies the labels that the Service will route traffic to.
    app: k8s  # This should match the labels of your Pod(s)
  ports:
    - protocol: TCP
      port: 80     # Port on the Service through which it will be accessible
      targetPort: 8080  # Port on the Pod where the service traffic will be forwarded
  type: NodePort # Specifies the type of Service. 
