apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: k8s 
spec:
  containers: 
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 200Mi
