apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo

spec:
 # scaleTargetRef: reference to scaled resource; 
 # horizontal pod autoscaler will learn the current resource consumption 
 # and will set the desired number of pods by using its Scale subresource.
 # CrossVersionObjectReference contains enough information to let you identify the referred resource.
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: hpa-k8s-deployment

 # minReplicas is the lower limit for the number of replicas to which the autoscaler can scale down. 
 # It defaults to 1 pod. 
 # Scaling is active as long as at least one metric value is available. 
 minReplicas: 1

 # maxReplicas is the upper limit for the number of pods that can be set by the autoscaler
 # cannot be smaller than MinReplicas.
 maxReplicas: 10
 
 # targetCPUUtilizationPercentage is the target average CPU utilization (represented as a percentage of requested CPU) 
 # over all the pods; if not specified the default autoscaling policy will be used.
 targetCPUUtilizationPercentage: 50