apiVersion: v1
kind: Pod
metadata:
  name: k8s-demo-pod-backend
  labels:
    env: backend
spec:
  containers:
  - name: k8s-demo-container
    image: vivek2508/k8s-demo:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"