apiVersion: v1
kind: Pod
metadata:
  name: k8s-demo-pod-frontend
  labels:
    env: frontend
spec:
  containers:
  - name: k8s-demo-container
    image: vivek2508/k8s-demo:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  
  # affinity: If specified, the pod's scheduling constraints
  affinity:
    # podAffinity: Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as some other pod(s)).
    podAffinity:
      # Defines a set of pods (namely those matching the labelSelector relative to the given namespace(s)) that this pod should be co-located (affinity) 
      # or not co-located (anti-affinity) with, where co-located is defined as running on a node whose value of the label with key matches that of any 
      # node on which a pod of the set of pods is running
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: env
            operator: In
            values:
            - backend
        # This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, 
        # where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the 
        # selected pods is running. Empty topologyKey is not allowed.
        # topologyKey: topology.kubernetes.io/zone
        topologyKey: kubernetes.io/hostname