apiVersion: apps/v1
kind: Deployment
metadata:
  app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: nginx-2
      namespace: default
      labels:
        app: myapp
    spec:
      containers: 
      - name: nginx-1
        image: nginx:1.14.2
        ports:
        - containerPort: 80
