apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: default
spec: 
  serviceName: redis
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-container
        image: redis:v1
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi  # Adjust the storage size as needed

